defaults:
  - _self_
  - launcher: local
  - data: pusht

world_model: ???
checkpoint_cache_dir: null
cache_dir: null
device: cuda
output_model_name: action_flow
subdir: ${hydra:job.id}

experiment:
  output_root: null
  task: pusht
  wm_variant: original
  policy_variant: flow
  variant: wm_${experiment.wm_variant}_policy_${experiment.policy_variant}
  use_run_dir_for_lightning: true

plan_config:
  horizon: 5

train_split: 0.9
seed: 3072
img_size: 224
embed_dim: 192
history_size: 1
num_preds: ${plan_config.horizon}
num_workers: 6
gradient_clip_val: 1.0

trainer:
  max_epochs: 100

loader:
  batch_size: 128
  num_workers: ${num_workers}
  persistent_workers: True
  prefetch_factor: 3
  pin_memory: True

optimizer:
  lr: 5e-5
  weight_decay: 1e-3

logging:
  wandb_every_n_steps: 50
  jsonl_every_n_steps: 50

action_model:
  _target_: module.ConditionalActionFlow
  condition_dim: ???
  action_dim: ???
  horizon: ???
  hidden_dim: 256
  depth: 4
  time_dim: 64
  sample_steps: 8
  stochastic_sample: true
