# @package _global_
# Local launcher configuration (no SLURM)

defaults:
  - override /hydra/launcher: basic

wandb:
  enabled: True
  config:
    entity: null
    project: lewm-flow-2x2
    group: ${experiment.task}/${experiment.wm_variant}/${experiment.policy_variant}
    name: ${experiment.task}_${experiment.wm_variant}_${experiment.policy_variant}_seed${seed}
    id: ${subdir}
    resume: allow
    log_model: False
    tags:
      - flow-2x2
      - ${experiment.task}
      - ${experiment.wm_variant}
      - ${experiment.policy_variant}
      - seed_${seed}
